
export const NOTE_CONSTANT = {
    CONFIRM : 'COMFIRM',
    CHANGE_CONTENT: 'CHANGE_CONTENT',
    CHANGE_LEVEL: 'CHANGE_LEVEL',
    EDIT: 'EDIT',
    REMOVE: 'REMOVE',
    TOGGLE_FORM: 'TOGGLE_FORM',
    CHANGE_STATUS: 'CHANGE_STATUS',
    CHANGE_QUERY_CONTENT: 'CHANGE_QUERY_CONTENT',
    CHANGE_QUERY_DATE: 'CHANGE_QUERY_DATE',
    CHANGE_QUERY_LEVEL: 'CHANGE_QUERY_LEVEL',
    CHANGE_QUERY_STATUS: 'CHANGE_QUERY_STATUS',
} 